<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-5VLC0MFK" ignored="0" name="Assertions Test" tests="4" failures="3" timestamp="12 Mar 2017 16:05:45 GMT" time="0.098" errors="0">
  <testcase name="assertFail" time="0.009" classname="com.rakesh.testng.training.testcases.AssertionsTestNGConcepts">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.rakesh.testng.training.testcases.AssertionsTestNGConcepts.assertFail(AssertionsTestNGConcepts.java:71)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- assertFail -->
  <testcase name="loginTest" time="0.008" classname="com.rakesh.testng.training.testcases.AssertionsTestNGConcepts"/>
  <testcase name="loginTest1" time="0.021" classname="com.rakesh.testng.training.testcases.AssertionsTestNGConcepts">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [WIPRO] but found [SAP]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [WIPRO] but found [SAP]
	at com.rakesh.testng.training.testcases.AssertionsTestNGConcepts.loginTest1(AssertionsTestNGConcepts.java:66)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- loginTest1 -->
  <testcase name="registrationTest" time="0.002" classname="com.rakesh.testng.training.testcases.AssertionsTestNGConcepts">
    <failure type="java.lang.AssertionError" message="Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed expected [true] but found [false]
	at com.rakesh.testng.training.testcases.AssertionsTestNGConcepts.registrationTest(AssertionsTestNGConcepts.java:33)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- registrationTest -->
</testsuite> <!-- Assertions Test -->
